export const naw = {
  schema_name: "naw",
  schema_version: "1.0",
  attributes: [
    "naam",
    "voorletters",
    "achternaam",
    "geslacht",
    "geboortedatum",
    "geboorteland",
    "bsn",
    "geldigheid_id",
    "burgerlijke_staat",
    "telefoonnummer",
    "email",
    "straat",
    "huisnummer",
    "toevoeging",
    "postcode",
    "woonplaats",
    "provincie",
    "land",
    "polisnummer",
    "verzekeraar",
    "mantelzorger_voornaam",
    "mantelzorger_tussenvoegsel",
    "mantelzorger_achternaam",
    "mantelzorger_telefoonnummer",
    "mantelzorger_email",
    "contactpersoon_voornaam",
    "contactpersoon_tussenvoegsel",
    "contactpersoon_achternaam",
    "contactpersoon_telefoonnummer",
    "contactpersoon_email",
    "huisarts_naam",
    "huisarts_straat",
    "huisarts_huisnnummer",
    "huisarts_toevoeging",
    "huisarts_telefoonnummer",
    "huisarts_UID",
    "huisarts_email",
  ],
};
